import {useEffect,useState} from 'react';
import {Routes,Route,NavLink,Link,useLocation} from 'react-router-dom';
import {AnimatePresence,motion} from 'framer-motion';
import {ArrowRight,ChevronDown,Camera,Menu,Quote,X} from 'lucide-react';

const studio={phone:'(804) 555-0147',email:'hello@vespertattoo.com',address:'1217 W Main Street, Richmond, VA 23220'};
const nav=['Artists','Gallery','Services','Reviews','FAQ','Contact'];
const gallery=[
 {style:'Black & Grey',pos:'22% 40%',h:'tall'},{style:'Fine Line',pos:'40% 40%',h:'short'},{style:'Realism',pos:'58% 45%',h:'mid'},
 {style:'Traditional',pos:'72% 42%',h:'short'},{style:'Color',pos:'82% 40%',h:'tall'},{style:'Portrait',pos:'60% 35%',h:'short'},
 {style:'Custom Work',pos:'28% 38%',h:'mid'},{style:'Fine Line',pos:'46% 38%',h:'tall'},{style:'Black & Grey',pos:'77% 40%',h:'mid'}];

function Seo({title,description}:{title:string,description:string}){useEffect(()=>{document.title=title;let m=document.querySelector('meta[name="description"]')||document.head.appendChild(document.createElement('meta'));m.setAttribute('name','description');m.setAttribute('content',description);[['property','og:title',title],['property','og:description',description],['property','og:image','/images/hero.png']].forEach(([a,n,c])=>{let e=document.querySelector(`meta[${a}="${n}"]`)||document.head.appendChild(document.createElement('meta'));e.setAttribute(a,n);e.setAttribute('content',c)});},[title,description]);return null}
function Header(){const[open,setOpen]=useState(false);return <><header><Link className="logo" to="/" onClick={()=>setOpen(false)}>VESPER<span>TATTOO CO.</span></Link><nav className={open?'open':''}>{nav.map(n=><NavLink key={n} to={'/'+n.toLowerCase()} onClick={()=>setOpen(false)}>{n}</NavLink>)}</nav><Link className="btn navcta" to="/contact">Book consultation <ArrowRight size={16}/></Link><button className="menubtn" onClick={()=>setOpen(!open)} aria-label="Toggle menu">{open?<X/>:<Menu/>}</button></header></>}
function Footer(){return <footer><div className="logo">VESPER<span>TATTOO CO.</span></div><p>Permanent art. Personal ritual.<br/>Made in Richmond, Virginia.</p><div><a href={'tel:'+studio.phone}> {studio.phone}</a><br/><a href={'mailto:'+studio.email}>{studio.email}</a></div><div className="social"><Camera/> <span>Instagram</span></div><small>© 2026 Vesper Tattoo Co. · Privacy · Accessibility</small></footer>}
function Layout(){const loc=useLocation();useEffect(()=>window.scrollTo(0,0),[loc.pathname]);return <><Header/><AnimatePresence mode="wait"><motion.main key={loc.pathname} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0}} transition={{duration:.35}}><Routes><Route path="/" element={<Home/>}/><Route path="/artists" element={<Artists/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/services" element={<Services/>}/><Route path="/reviews" element={<Reviews/>}/><Route path="/faq" element={<Faq/>}/><Route path="/contact" element={<Contact/>}/></Routes></motion.main></AnimatePresence><Footer/><Link className="mobile-book" to="/contact">Book consultation <ArrowRight size={17}/></Link></>}
const SectionTitle=({kicker,title,copy}:{kicker:string,title:string,copy?:string})=><div className="section-title"><span>{kicker}</span><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>;
function Home(){return <><Seo title="Vesper Tattoo Co. | Premium Tattoo Shop in Richmond, VA" description="Richmond's private, award-winning tattoo studio for custom black & grey, fine line, realism and color work. Book your consultation."/>
<section className="hero"><div className="hero-bg"/><div className="hero-copy"><span className="eyebrow">Richmond, Virginia · Est. 2012</span><h1>Art, made<br/><em>permanent.</em></h1><p>One-of-one tattoos, created with intention by artists who take the time to understand your story.</p><div className="actions"><Link className="btn" to="/contact">Book a consultation <ArrowRight size={17}/></Link><Link className="text-link" to="/gallery">Explore the work</Link></div></div><div className="hero-proof"><strong>4.9</strong><span>★★★★★<br/>327 Google reviews</span></div></section>
<section><SectionTitle kicker="Our craft" title="Find your visual language." copy="From quiet, precise linework to bold full-color compositions, every piece begins with your idea and becomes unmistakably yours."/><div className="style-grid">{['Black & grey','Fine line','Realism','Color & neo-traditional'].map((s,i)=><Link to="/gallery" className="style-card" key={s}><span>0{i+1}</span><h3>{s}</h3><ArrowRight/></Link>)}</div></section>
<section className="split"><div className="studio-img"/><div><SectionTitle kicker="The Vesper standard" title="A better kind of tattoo experience."/><p>Private rooms. Unhurried consultations. Hospital-grade sterilization. We built Vesper around the belief that world-class art deserves world-class care.</p><div className="stats"><b>14<small>Years in Richmond</small></b><b>3<small>Awarded artists</small></b><b>5k+<small>Original pieces</small></b></div><Link className="text-link" to="/artists">Meet the artists <ArrowRight size={15}/></Link></div></section>
<Testimonials/><InstagramGrid/><FaqPreview/><Cta/></>}
function Testimonials(){return <section className="testimonial"><Quote/><p>“From the first sketch to the final reveal, I felt completely heard. The piece is more beautiful than I could have imagined.”</p><div className="stars">★★★★★</div><span>— Maya R. · Fine line botanical</span><div className="dots"><i/><i/><i/></div></section>}
function InstagramGrid(){return <section><SectionTitle kicker="@vespertattoo" title="Fresh from the studio."/><div className="insta-grid">{gallery.slice(0,5).map((g,i)=><div key={i} style={{backgroundPosition:g.pos}}><Camera/></div>)}</div></section>}
function FaqPreview(){return <section><SectionTitle kicker="Good to know" title="Before you book."/><div className="faq-grid">{['How does the consultation process work?','What is your deposit policy?','How should I prepare?'].map(q=><details key={q}><summary>{q}<ChevronDown/></summary><p>Start with our short consultation form. We’ll review your idea, recommend the right artist, and follow up within two business days.</p></details>)}</div><Link className="text-link" to="/faq">View all FAQs <ArrowRight size={15}/></Link></section>}
function Cta(){return <section className="cta"><span>Your idea deserves time.</span><h2>Let’s make something<br/><em>worth keeping.</em></h2><Link className="btn light" to="/contact">Start your consultation <ArrowRight/></Link></section>}
function PageHero({kicker,title,copy}:{kicker:string,title:string,copy:string}){return <section className="page-hero"><span>{kicker}</span><h1>{title}</h1><p>{copy}</p></section>}
const people=[['Amara Reid','Black & grey · Botanical · Fine line','left'],['Mateo Cruz','Realism · Portrait · Black & grey','center'],['Kai Tan','Color · Neo-traditional · Custom','right']];
function Artists(){return <><Seo title="Tattoo Artists in Richmond, VA | Vesper Tattoo Co." description="Meet Vesper's licensed Richmond tattoo artists specializing in fine line, realism, portrait, color, and custom tattoos."/><PageHero kicker="The artists" title="Three perspectives. One standard." copy="A small, deeply experienced collective united by obsessive craft and genuine care."/><section className="artist-list">{people.map((p,i)=><article className="artist" key={p[0]}><div className={'artist-photo '+p[2]}/><div><span>0{i+1}</span><h2>{p[0]}</h2><p>{p[1]}</p><p className="bio">{['Amara creates delicate, flowing work inspired by the natural world. Her calm, collaborative process is as considered as every line.','Known for emotional portraiture and sculptural contrast, Mateo turns meaningful reference into timeless black-and-grey work.','Kai brings painterly color and unexpected composition to custom pieces that feel both playful and deeply personal.'][i]}</p><div className="actions"><Link className="btn" to="/contact">Book with {p[0].split(' ')[0]}</Link><a className="text-link" href="#">Instagram</a></div></div></article>)}</section><Cta/></>}
function Gallery(){const[f,setF]=useState('All'),[light,setLight]=useState<number|null>(null);let fs=['All','Black & Grey','Color','Traditional','Fine Line','Realism','Portrait','Custom Work'];let shown=gallery.filter(g=>f==='All'||g.style===f);return <><Seo title="Tattoo Gallery | Richmond Tattoo Shop | Vesper" description="Explore custom tattoos by Vesper Tattoo Co. in Richmond, VA: black and grey, color, traditional, fine line, realism and portrait work."/><PageHero kicker="Selected work" title="Every piece, one of one." copy="A living archive of the stories entrusted to us."/><div className="filters">{fs.map(x=><button className={f===x?'active':''} onClick={()=>setF(x)} key={x}>{x}</button>)}</div><section className="masonry">{shown.map((g,i)=><button className={'gallery-item '+g.h} key={i} onClick={()=>setLight(i)} style={{backgroundPosition:g.pos}} aria-label={'View '+g.style}><span>{g.style}<ArrowRight/></span></button>)}</section>{light!==null&&<div className="lightbox" onClick={()=>setLight(null)}><button aria-label="Close"><X/></button><div style={{backgroundPosition:shown[light].pos}}/><p>{shown[light].style} · Richmond, VA</p></div>}<Cta/></>}
function Services(){let cards=[['Custom tattooing','From $200','Original work developed around your story, placement, and body.'],['Fine line','From $180','Delicate, precise compositions with thoughtful longevity.'],['Portrait & realism','From $350','High-detail work, typically reserved as half or full-day sessions.'],['Cover-ups','By consultation','Strategic design that transforms what is there into something new.']];return <><Seo title="Tattoo Services & Pricing | Richmond, VA | Vesper" description="Custom tattoo services in Richmond, VA. Learn about fine line, realism, cover-ups, pricing, consultations, policies and tattoo aftercare."/><PageHero kicker="Services" title="Built around the work." copy="Transparent guidance, considered process, and no shortcuts—ever."/><section className="service-grid">{cards.map(c=><article><span>{c[1]}</span><h3>{c[0]}</h3><p>{c[2]}</p></article>)}</section><section className="process"><SectionTitle kicker="The process" title="From idea to healed art."/><ol>{[['01','Tell us your idea','Share references, placement, size, and what matters to you.'],['02','Meet your artist','We shape the concept and reserve your appointment with a deposit.'],['03','Create together','Your artist presents the final direction and makes thoughtful refinements.'],['04','Heal beautifully','Leave with complete aftercare guidance and ongoing support.']].map(x=><li><b>{x[0]}</b><h3>{x[1]}</h3><p>{x[2]}</p></li>)}</ol></section><section className="policy"><div><SectionTitle kicker="Studio policy" title="Clear expectations. Better work."/><p>Appointments require a non-refundable deposit applied to your final session. Please bring valid photo ID; clients must be 18+. We maintain single-use supplies and hospital-grade sterilization throughout the studio.</p></div><div><SectionTitle kicker="Aftercare" title="Protect the investment."/><p>Keep your bandage on as directed, wash gently, moisturize sparingly, and avoid soaking or direct sun while healing. You’ll receive artist-specific instructions after your session.</p></div></section><Cta/></>}
const reviews=[['“I traveled three hours for Amara and would do it again tomorrow. The studio is immaculate and the work is unreal.”','Nia W.'],['“Mateo captured my dad’s expression perfectly. It’s more than a tattoo—it feels like carrying him with me.”','Jordan L.'],['“The most respectful, comfortable studio experience I’ve had. Kai made the whole process feel easy.”','Alex P.'],['“Every detail—from the consultation to aftercare—felt thoughtful and premium.”','Samantha K.'],['“My fine-line piece healed beautifully and still looks crisp two years later.”','Claire D.'],['“No ego, no rush, just truly exceptional artists.”','Marcus T.']];
function Reviews(){return <><Seo title="Vesper Tattoo Reviews | Richmond Tattoo Shop" description="Read client reviews for Vesper Tattoo Co., a 4.9-star custom tattoo studio in Richmond, Virginia."/><PageHero kicker="Client stories" title="The feeling stays, too." copy="327 reviews. Hundreds of stories. One standard of care."/><section className="review-summary"><strong>4.9</strong><div><div className="stars">★★★★★</div><p>Based on 327 Google reviews</p><button className="text-link">View on Google <ArrowRight/></button></div></section><section className="reviews-grid">{reviews.map(r=><article><div className="stars">★★★★★</div><p>{r[0]}</p><span>{r[1]} · Verified client</span></article>)}</section><Cta/></>}
const faqs=[['How do I book?','Complete the consultation form with your idea, placement, approximate size, and reference images. We’ll pair you with the right artist and reply within two business days.'],['What is the deposit policy?','A non-refundable deposit secures your appointment and is applied to the final cost of your tattoo. Amounts vary by project and artist.'],['How should I prepare for my appointment?','Sleep well, eat a complete meal, hydrate, wear comfortable clothing that provides easy access to the area, and avoid alcohol for 24 hours.'],['Do you accept walk-ins?','We are primarily appointment-only. Occasional walk-in days are announced on Instagram.'],['What is your cancellation policy?','Please give at least 72 hours notice to reschedule. Late cancellations or no-shows forfeit the deposit.'],['How much will my tattoo cost?','Our shop minimum is $180. Final pricing depends on artist, size, placement, complexity, and time. You’ll receive guidance during consultation.'],['Can I bring a guest?','One adult guest is welcome when space allows. For focus and safety, we may ask guests to wait in the lobby.'],['Is your studio accessible?','Yes. Our main entrance and studio rooms are step-free. Tell us about any accommodations when booking.']];
function Faq(){return <><Seo title="Tattoo FAQ | Vesper Tattoo Co. Richmond" description="Answers about booking, tattoo deposits, preparation, walk-ins, pricing, cancellations and aftercare at Vesper Tattoo Co. Richmond."/><PageHero kicker="Frequently asked" title="No mystery. Just good information." copy="Everything you need to feel ready, from first message to fully healed."/><section className="faq-all">{faqs.map((q,i)=><details open={i===0}><summary>{q[0]}<ChevronDown/></summary><p>{q[1]}</p></details>)}</section><Cta/></>}
function Contact(){const[done,setDone]=useState(false);return <><Seo title="Book a Tattoo Consultation | Richmond, VA | Vesper" description="Request a tattoo consultation with Vesper Tattoo Co. in Richmond, VA. Tell us your idea and hear back within two business days."/><PageHero kicker="Start a conversation" title="Tell us what you’re imagining." copy="No perfect brief required. Bring the spark—we’ll help shape the rest."/><section className="contact-grid"><form onSubmit={e=>{e.preventDefault();setDone(true)}}>{done?<div className="success"><h2>We’ve got your idea.</h2><p>Our studio coordinator will be in touch within two business days.</p></div>:<><div className="form-row"><label>First name<input required/></label><label>Last name<input required/></label></div><label>Email<input required type="email"/></label><label>Phone<input required type="tel"/></label><label>Preferred artist<select><option>No preference</option>{people.map(p=><option key={p[0]}>{p[0]}</option>)}</select></label><label>Tell us about your idea<textarea required rows={5} placeholder="Style, subject, placement, approximate size..."/></label><label>Reference images<input type="file" multiple/></label><button className="btn">Send consultation request <ArrowRight/></button><small>By submitting, you agree to be contacted about your request. No spam, ever.</small></>}</form><aside><h3>Visit the studio</h3><p>{studio.address}</p><a href={'tel:'+studio.phone}>{studio.phone}</a><a href={'mailto:'+studio.email}>{studio.email}</a><h3>Hours</h3><p>Tue–Sat · 11am–7pm<br/>Sun–Mon · By appointment</p><div className="map"><iframe title="Map of Vesper Tattoo Co. in Richmond" loading="lazy" src="https://www.google.com/maps?q=1217+W+Main+Street+Richmond+VA&output=embed"/></div><a className="text-link" href="#"><Camera/> Follow @vespertattoo</a></aside></section></>}
function Schema(){useEffect(()=>{let s=document.createElement('script');s.type='application/ld+json';s.textContent=JSON.stringify({'@context':'https://schema.org','@type':'TattooParlor',name:'Vesper Tattoo Co.',image:'/images/hero.png',telephone:studio.phone,email:studio.email,address:{'@type':'PostalAddress',streetAddress:'1217 W Main Street',addressLocality:'Richmond',addressRegion:'VA',postalCode:'23220',addressCountry:'US'},priceRange:'$$$',openingHours:'Tu-Sa 11:00-19:00',aggregateRating:{'@type':'AggregateRating',ratingValue:'4.9',reviewCount:'327'}});document.head.appendChild(s);return()=>s.remove()},[]);return null}
export default function App(){return <><Schema/><Layout/></>}
